services:
  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=islanders
      - POSTGRES_USER=islanders
      - POSTGRES_PASSWORD=islanders
    volumes:
      - ./islanders-server/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - 5432:5432

  islanders-server:
    build:
      context: .
      dockerfile: ./islanders-server/Dockerfile
    env_file:
      - ./islanders-server/.env
    restart: unless-stopped
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=postgres://islanders:islanders@postgres:5432/islanders
    depends_on:
      - postgres

  islanders-client:
    build:
      context: .
      dockerfile: ./islanders-client/Dockerfile
    env_file:
      - ./islanders-client/.env
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - islanders-server
