name: Docker Image CI

on: [push]

jobs:
  build_test_project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Compose Build
        run: docker compose build
